[package]
name = "rucola"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# General TUI
crossterm = "0.27.0"
ratatui = {version = "0.26.1", features = ["serde"]}
tui-textarea = "0.4.0"
# Command line parsing
clap = {version = "^4.5", features = ["derive"]}
expanduser = "^1.2"
# Opening
open = "^5"
# Parsing
regex = "1.10.3"
walkdir = "2.5.0"
fuzzy-matcher = "^0.3"
itertools = "^0.12"
# Error handling
eyre = "0.6.12"
color-eyre = "0.5.7"
# Config
serde = { version = "1.0", features = ["derive"] }
confy = "^0.6"

