[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.30.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew", "msi"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
# Customize the Homebrew formula name
formula = "rucola"
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# A GitHub repo to push Homebrew formulas to
tap = "Linus-Mussmaecher/homebrew-tap"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
