name: Compile and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Update rust
        run: rustup update stable && rustup default stable
      - name: Update cargo to latest dependencies
        run: cargo update --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
  clippy_lint:
    name: Clippy
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --verbose
