name: Compile and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Update rust
        run: rustup update stable && rustup default stable
      - name: Update cargo
        run: cargo update --verbose
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

  build_and_test:
    name: Rust Project Build and Test
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  clippy_lint:
    name: Rust Project Clippy
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clippy
      run: cargo clippy --verbose
